// apps/web/src/components/mini-graph.tsx
import type { WorkoutSegment, SegmentType } from '@/lib/types';

const SEGMENT_COLORS: Record<SegmentType, string> = {
  work: '#3b82f6',
  rest: '#6b7280',
  warmup: '#22c55e',
  cooldown: '#eab308',
};

/** Reference pace for scaling bar heights (very slow = 3:00/500m = 1800 tenths) */
const MAX_PACE = 1800;
/** Minimum bar height as a fraction of total height */
const MIN_HEIGHT_FRACTION = 0.15;

function getBarHeight(segment: WorkoutSegment, totalHeight: number): number {
  if (!segment.target_split) return totalHeight * MIN_HEIGHT_FRACTION;
  const pace = segment.target_split.pace;
  // Lower pace = more intense = taller bar
  const intensity = Math.max(0, Math.min(1, 1 - pace / MAX_PACE));
  const fraction = MIN_HEIGHT_FRACTION + intensity * (1 - MIN_HEIGHT_FRACTION);
  return Math.round(fraction * totalHeight);
}

function getBarWidth(segment: WorkoutSegment): number {
  const repeat = segment.repeat || 1;
  return segment.duration_value * repeat;
}

interface MiniGraphProps {
  segments: WorkoutSegment[];
  height?: number;
}

export function MiniGraph({ segments, height = 48 }: MiniGraphProps) {
  if (segments.length === 0) return null;

  const totalWidth = segments.reduce((sum, seg) => sum + getBarWidth(seg), 0);
  if (totalWidth === 0) return null;

  return (
    <div
      className="flex items-end gap-px overflow-hidden rounded"
      style={{ height }}
    >
      {segments.map((segment, i) => {
        const barHeight = getBarHeight(segment, height);
        const widthPct = (getBarWidth(segment) / totalWidth) * 100;

        return (
          <div
            key={i}
            className="rounded-sm"
            style={{
              height: barHeight,
              width: `${widthPct}%`,
              minWidth: 2,
              backgroundColor: SEGMENT_COLORS[segment.type],
            }}
          />
        );
      })}
    </div>
  );
}

// apps/web/src/lib/components/MiniGraph.svelte
<script lang="ts">
	import type { WorkoutSegment } from '$lib/types';

	interface Props {
		segments: WorkoutSegment[];
		height?: number;
	}

	let { segments, height = 48 }: Props = $props();

	const segmentColors: Record<string, string> = {
		work: '#3b82f6',
		rest: '#6b7280',
		warmup: '#22c55e',
		cooldown: '#eab308'
	};

	// svelte-ignore state_referenced_locally
	const maxBarHeight = height;
	// svelte-ignore state_referenced_locally
	const minBarHeight = Math.round(height * 0.25);

	const bars = $derived.by(() => {
		const paces = segments
			.filter((s) => s.target_split)
			.map((s) => s.target_split!.pace);

		const minPace = paces.length > 0 ? Math.min(...paces) : 1200;
		const maxPace = paces.length > 0 ? Math.max(...paces) : 1800;
		const paceRange = maxPace - minPace || 1;

		return segments.map((seg) => {
			let barHeight: number;
			if (seg.target_split) {
				const normalizedIntensity = 1 - (seg.target_split.pace - minPace) / paceRange;
				barHeight = minBarHeight + normalizedIntensity * (maxBarHeight - minBarHeight);
			} else if (seg.type === 'rest') {
				barHeight = minBarHeight;
			} else {
				barHeight = (minBarHeight + maxBarHeight) / 2;
			}

			let widthWeight = seg.duration_value;
			if (seg.duration_type === 'distance') {
				widthWeight = seg.duration_value / 5;
			}

			return {
				height: barHeight,
				widthWeight: widthWeight * (seg.repeat || 1),
				color: segmentColors[seg.type] ?? segmentColors.work
			};
		});
	});

	const totalWeight = $derived(bars.reduce((sum, b) => sum + b.widthWeight, 0) || 1);
</script>

<div class="flex items-end gap-px overflow-hidden" style="height: {height}px;">
	{#each bars as bar}
		<div
			style="flex: {bar.widthWeight / totalWeight}; height: {bar.height}px; background-color: {bar.color}; min-width: 3px;"
		></div>
	{/each}
</div>
