// apps/web/src/components/ui/segment-card.tsx
import type { WorkoutSegment, SegmentType } from '@/lib/types';
import { formatSegmentType, formatSegmentDuration, formatPace } from '@/lib/utils/format';
import { paceTenthsToWatts, formatWatts } from '@/lib/utils/ftp';

const SEGMENT_BG: Record<SegmentType, string> = {
  work: 'border-blue-500/30 bg-blue-500/5',
  rest: 'border-gray-500/30 bg-gray-500/5',
  warmup: 'border-emerald-500/30 bg-emerald-500/5',
  cooldown: 'border-yellow-500/30 bg-yellow-500/5',
};

const SEGMENT_DOT: Record<SegmentType, string> = {
  work: 'bg-blue-500',
  rest: 'bg-gray-500',
  warmup: 'bg-emerald-500',
  cooldown: 'bg-yellow-500',
};

interface SegmentCardProps {
  segment: WorkoutSegment;
  index: number;
  instanceLabel?: string;
}

export function SegmentCard({ segment, index, instanceLabel }: SegmentCardProps) {
  return (
    <div className={`rounded-lg border p-3 ${SEGMENT_BG[segment.type]}`}>
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className={`h-2.5 w-2.5 rounded-full ${SEGMENT_DOT[segment.type]}`} />
          <span className="text-sm font-medium text-white">
            {instanceLabel ?? `#${index + 1}`} {formatSegmentType(segment.type)}
          </span>
        </div>
        <span className="text-sm text-gray-400">{formatSegmentDuration(segment)}</span>
      </div>

      <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-400">
        {segment.target_split && (
          <span>
            Pace: {formatPace(segment.target_split.pace)}/500m ({formatWatts(paceTenthsToWatts(segment.target_split.pace))})
          </span>
        )}
        {segment.target_stroke_rate && (
          <span>
            SPM: {segment.target_stroke_rate.min}–{segment.target_stroke_rate.max}
          </span>
        )}
        {segment.target_hr_zone && (
          <span>HR Zone {segment.target_hr_zone}</span>
        )}
      </div>

      {segment.messages && segment.messages.length > 0 && (
        <div className="mt-2 space-y-1">
          {segment.messages.map((msg, i) => (
            <p key={i} className="text-xs italic text-gray-500">
              &ldquo;{msg.text}&rdquo;
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

// apps/web/src/lib/components/SegmentCard.svelte
<script lang="ts">
	import type { WorkoutSegment } from '$lib/types';
	import { formatPace, formatSegmentDuration, formatSegmentType } from '$lib/utils/format';
	import { paceTenthsToWatts, formatWatts, getHrZoneFromNumber, getHrZoneLabel } from '$lib/utils/ftp';

	interface Props {
		segment: WorkoutSegment;
		index: number;
	}

	let { segment, index }: Props = $props();

	const borderColors: Record<string, string> = {
		work: 'border-l-blue-500',
		rest: 'border-l-gray-500',
		warmup: 'border-l-emerald-500',
		cooldown: 'border-l-yellow-500'
	};

	const wattsDisplay = $derived(
		segment.target_split
			? formatWatts(paceTenthsToWatts(segment.target_split.pace))
			: null
	);

	const hrZoneDisplay = $derived(
		segment.target_hr_zone
			? (() => { const name = getHrZoneFromNumber(segment.target_hr_zone!); return name ? getHrZoneLabel(name) : null; })()
			: null
	);
</script>

<div class="rounded-lg border border-gray-800 bg-gray-900 border-l-4 {borderColors[segment.type] ?? 'border-l-gray-500'}">
	<div class="px-4 py-3">
		<div class="flex items-center justify-between">
			<div class="flex items-center gap-3">
				<span class="text-sm font-medium text-gray-600">{index + 1}</span>
				<span class="text-sm font-semibold text-white">{formatSegmentType(segment.type)}</span>
				<span class="font-mono text-sm text-gray-400">{formatSegmentDuration(segment)}</span>
				{#if segment.repeat > 1}
					<span class="rounded bg-gray-800 px-2 py-0.5 text-xs text-gray-400">
						x{segment.repeat}
					</span>
				{/if}
			</div>
			<div class="flex items-center gap-4 text-sm text-gray-400">
				{#if segment.target_split}
					<span class="font-mono">{formatPace(segment.target_split.pace)}/500m</span>
					{#if wattsDisplay}
						<span class="text-xs text-gray-600">{wattsDisplay}</span>
					{/if}
				{/if}
				{#if segment.target_stroke_rate}
					<span>{segment.target_stroke_rate.min} spm</span>
				{/if}
				{#if hrZoneDisplay}
					<span class="text-xs rounded bg-blue-500/10 px-2 py-0.5 text-blue-400">{hrZoneDisplay}</span>
				{/if}
			</div>
		</div>

		<!-- Coaching cues -->
		{#if segment.messages && segment.messages.length > 0}
			<div class="mt-2 flex flex-wrap gap-1.5">
				{#each segment.messages as msg}
					<span class="inline-flex items-center gap-1 rounded-full bg-gray-800 px-2.5 py-0.5 text-xs text-gray-400">
						{#if msg.trigger_type === 'start'}
							<span class="text-emerald-500">Start:</span>
						{:else if msg.trigger_type === 'end'}
							<span class="text-red-400">End:</span>
						{:else if msg.trigger_type === 'time'}
							<span class="text-blue-400">@{msg.trigger_value}s:</span>
						{:else if msg.trigger_type === 'distance'}
							<span class="text-blue-400">@{msg.trigger_value}m:</span>
						{/if}
						{msg.text}
					</span>
				{/each}
			</div>
		{/if}
	</div>
</div>
