// apps/web/src/lib/components/StatsBar.svelte
<script lang="ts">
	import type { WorkoutSegment } from '$lib/types';
	import { formatDuration, formatDistance } from '$lib/utils/format';
	import { computeTotalTime, computeTotalDistance, computeSegmentCount } from '$lib/utils/workout';

	interface Props {
		segments: WorkoutSegment[];
	}

	let { segments }: Props = $props();

	const totalTime = $derived(computeTotalTime(segments));
	const totalDistance = $derived(computeTotalDistance(segments));
	const segmentCount = $derived(computeSegmentCount(segments));
</script>

<div class="flex items-center gap-8 rounded-xl border border-gray-800 bg-gray-900 px-6 py-4">
	{#if totalTime}
		<div>
			<p class="text-xs text-gray-500 uppercase tracking-wider">Time</p>
			<p class="font-mono text-lg font-bold text-white">{formatDuration(totalTime)}</p>
		</div>
	{/if}
	{#if totalDistance}
		<div>
			<p class="text-xs text-gray-500 uppercase tracking-wider">Distance</p>
			<p class="font-mono text-lg font-bold text-white">{formatDistance(totalDistance)}</p>
		</div>
	{/if}
	<div>
		<p class="text-xs text-gray-500 uppercase tracking-wider">Segments</p>
		<p class="font-mono text-lg font-bold text-white">{segmentCount}</p>
	</div>
</div>

// apps/web/src/components/ui/stats-bar.tsx
import type { WorkoutSegment } from '@/lib/types';
import { formatDuration, formatDistance } from '@/lib/utils/format';
import { computeTotalTime, computeTotalDistance, computeSegmentCount } from '@/lib/utils/workout';

interface StatsBarProps {
  segments: WorkoutSegment[];
  forkCount?: number;
}

export function StatsBar({ segments, forkCount }: StatsBarProps) {
  const totalTime = computeTotalTime(segments);
  const totalDistance = computeTotalDistance(segments);
  const segmentCount = computeSegmentCount(segments);

  const stats = [
    ...(totalTime !== null ? [{ label: 'TIME', value: formatDuration(totalTime) }] : []),
    ...(totalDistance !== null ? [{ label: 'DISTANCE', value: formatDistance(totalDistance) }] : []),
    { label: 'SEGMENTS', value: String(segmentCount) },
    ...(forkCount !== undefined ? [{ label: 'FORKS', value: String(forkCount) }] : []),
  ];

  return (
    <div className="flex flex-wrap gap-3">
      {stats.map((stat) => (
        <div
          key={stat.label}
          className="min-w-[100px] rounded-lg border border-gray-800 bg-gray-900 p-4"
        >
          <span className="text-xs uppercase tracking-wider text-gray-500">{stat.label}</span>
          <div className="mt-1 font-mono text-2xl font-bold text-white">{stat.value}</div>
        </div>
      ))}
    </div>
  );
}
