// apps/web/src/app/workouts/[id]/page.tsx
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { createSupabaseServer, getUser } from '@/lib/supabase/server';
import type { Workout, WorkoutSegment } from '@/lib/types';
import { normalizeWorkoutSegments } from '@/lib/types';
import { formatWorkoutType } from '@/lib/utils/format';
import { WorkoutGraph } from '@/components/workout-graph';
import { StatsBar } from '@/components/ui/stats-bar';
import { SegmentCard } from '@/components/ui/segment-card';
import { WorkoutDetailActions } from './actions';

interface PageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const supabase = await createSupabaseServer();
  const { data } = await supabase.from('workouts').select('title, description').eq('id', id).eq('is_public', true).single();

  if (!data) return { title: 'Workout Not Found — RowCraft' };

  return {
    title: `${data.title} — RowCraft`,
    description: data.description || 'A RowCraft workout',
    openGraph: {
      title: data.title,
      description: data.description || 'A RowCraft workout',
      type: 'article',
    },
  };
}

/** Expand segments: if a segment has repeat > 1, produce N copies */
function expandSegments(segments: WorkoutSegment[]): { segment: WorkoutSegment; label: string }[] {
  const result: { segment: WorkoutSegment; label: string }[] = [];
  let counter = 1;

  for (const seg of segments) {
    const repeat = seg.repeat || 1;
    for (let r = 0; r < repeat; r++) {
      result.push({
        segment: { ...seg, repeat: 1 },
        label: `#${counter}`,
      });
      counter++;
    }
  }

  return result;
}

export default async function WorkoutDetailPage({ params }: PageProps) {
  const { id } = await params;
  const supabase = await createSupabaseServer();
  const user = await getUser();

  const userId = user?.id;
  let query = supabase.from('workouts').select('*').eq('id', id);
  if (userId) {
    query = query.or(`is_public.eq.true,author_id.eq.${userId}`);
  } else {
    query = query.eq('is_public', true);
  }
  const { data } = await query.single();

  if (!data) notFound();

  const workout: Workout = {
    ...data,
    segments: normalizeWorkoutSegments(data.segments ?? []),
  };

  const expandedSegments = expandSegments(workout.segments);
  const isOwner = user?.id === workout.author_id;

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Graph */}
      <div className="mb-6">
        <WorkoutGraph segments={workout.segments} />
      </div>

      {/* Title + badges */}
      <div className="mb-4 flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white">{workout.title}</h1>
          <div className="mt-2 flex items-center gap-2">
            <span className="rounded-full bg-gray-800 px-3 py-1 text-xs font-medium text-gray-400">
              {formatWorkoutType(workout.workout_type)}
            </span>
            {workout.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-full bg-gray-800 px-2 py-0.5 text-xs text-gray-500"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
        <WorkoutDetailActions workoutId={workout.id} isOwner={isOwner} isLoggedIn={!!user} />
      </div>

      {/* Description */}
      {workout.description && (
        <p className="mb-6 text-gray-400">{workout.description}</p>
      )}

      {/* Stats */}
      <div className="mb-8">
        <StatsBar segments={workout.segments} />
      </div>

      {/* Segments */}
      <h2 className="mb-4 text-lg font-semibold text-white">Segments</h2>
      <div className="space-y-3">
        {expandedSegments.map(({ segment, label }, i) => (
          <SegmentCard key={i} segment={segment} index={i} instanceLabel={label} />
        ))}
      </div>

      {/* CTA */}
      <div className="mt-12 rounded-xl border border-blue-500/30 bg-blue-500/5 p-6 text-center">
        <h3 className="text-lg font-semibold text-white">Ready to row?</h3>
        <p className="mt-1 text-sm text-gray-400">
          Open RowCraft on your phone and connect to your PM5 to start this workout.
        </p>
      </div>
    </div>
  );
}

// apps/web/src/routes/workouts/[id]/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import WorkoutGraphHero from '$lib/components/WorkoutGraphHero.svelte';
	import StatsBar from '$lib/components/StatsBar.svelte';
	import SegmentCard from '$lib/components/SegmentCard.svelte';
	import { formatWorkoutType } from '$lib/utils/format';
	import type { Workout } from '$lib/types';

	let { data } = $props();

	const workout: Workout = $derived(data.workout);
	const isOwner = $derived(data.userId === workout.author_id);
	let forking = $state(false);
	let shareMessage = $state('');

	async function forkWorkout() {
		if (!data.userId) return;
		forking = true;
		try {
			const { supabase } = data;
			if (!supabase) return;
			const { data: forkedWorkout, error: insertError } = await supabase
				.from('workouts')
				.insert({
					author_id: data.userId,
					title: workout.title,
					description: workout.description,
					workout_type: workout.workout_type,
					segments: workout.segments,
					tags: workout.tags,
					is_public: false,
					forked_from: workout.id
				})
				.select()
				.single();

			if (insertError) throw insertError;
			await supabase.rpc('increment_fork_count', { workout_id: workout.id });
			goto(`/workouts/${forkedWorkout.id}`);
		} catch (err) {
			console.error('Fork failed:', err);
		} finally {
			forking = false;
		}
	}

	async function shareWorkout() {
		try {
			await navigator.clipboard.writeText(window.location.href);
			shareMessage = 'Link copied!';
			setTimeout(() => { shareMessage = ''; }, 2000);
		} catch {
			shareMessage = 'Copy failed — copy the URL manually';
			setTimeout(() => { shareMessage = ''; }, 3000);
		}
	}
</script>

<svelte:head>
	<title>{workout.title} - RowCraft</title>
</svelte:head>

<div class="mx-auto max-w-4xl px-4 py-6 sm:px-6 lg:px-8 space-y-6">
	<!-- Hero graph -->
	{#if workout.segments?.length > 0}
		<WorkoutGraphHero segments={workout.segments} />
	{/if}

	<!-- Title + metadata -->
	<div>
		<div class="flex items-start justify-between gap-4">
			<div>
				<div class="flex items-center gap-3">
					<h1 class="text-2xl font-bold text-white">{workout.title}</h1>
					<span class="rounded-full bg-blue-500/10 px-3 py-1 text-xs font-medium text-blue-400">
						{formatWorkoutType(workout.workout_type)}
					</span>
				</div>
				{#if workout.description}
					<p class="mt-3 text-gray-400">{workout.description}</p>
				{/if}
				{#if workout.tags?.length > 0}
					<div class="mt-3 flex flex-wrap gap-2">
						{#each workout.tags as tag}
							<span class="rounded-full border border-gray-700 px-3 py-1 text-xs text-gray-400">
								{tag}
							</span>
						{/each}
					</div>
				{/if}
			</div>

			<!-- Actions -->
			<div class="flex items-center gap-2 shrink-0">
				{#if shareMessage}
					<span class="text-sm text-emerald-400">{shareMessage}</span>
				{/if}
				<button
					onclick={shareWorkout}
					class="rounded-lg border border-gray-700 px-3 py-2 text-sm text-gray-400 transition-colors hover:border-gray-600 hover:text-white"
				>
					Share
				</button>
				{#if !isOwner && data.userId}
					<button
						onclick={forkWorkout}
						disabled={forking}
						class="rounded-lg bg-gray-800 px-3 py-2 text-sm text-white transition-colors hover:bg-gray-700 disabled:opacity-50"
					>
						{forking ? 'Forking...' : `Fork (${workout.fork_count ?? 0})`}
					</button>
				{/if}
				{#if isOwner}
					<a
						href="/builder?edit={workout.id}"
						class="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white transition-colors hover:bg-blue-500"
					>
						Edit
					</a>
				{/if}
			</div>
		</div>
	</div>

	<!-- Stats bar -->
	{#if workout.segments?.length > 0}
		<StatsBar segments={workout.segments} />
	{/if}

	<!-- Segment list -->
	{#if workout.segments?.length > 0}
		<div>
			<h2 class="mb-3 text-lg font-semibold text-white">Segments</h2>
			<div class="space-y-2">
				{#each workout.segments as segment, i}
					<SegmentCard {segment} index={i} />
				{/each}
			</div>
		</div>
	{/if}

	<!-- Mobile app prompt -->
	<div class="rounded-xl border border-blue-500/20 bg-blue-500/5 p-6 text-center">
		<p class="text-lg font-semibold text-white">Ready to row?</p>
		<p class="mt-2 text-sm text-gray-400">
			Open RowCraft on your phone, connect your PM5, and start this workout with live pacing guidance.
		</p>
	</div>
</div>
